
/**
* ListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MessageServer.idl
* Tuesday, September 8, 2015 2:56:05 PM CDT
*/

public interface ListenerOperations 
{
  void message (String msg);
} // interface ListenerOperations
